import Link from "next/link";
import { ArrowLeft, FileText, ShieldAlert, Sparkles } from "lucide-react";

import { BrandMark } from "@/components/brand-mark";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

const sections = [
  {
    title: "Operator and scope",
    body: [
      "ReelFit AI is operated by SWEET MOTION in Australia. These Terms apply to your use of the ReelFit AI website, app experience, saved history, billing flows, and related product features."
    ]
  },
  {
    title: "What the service does",
    body: [
      "ReelFit AI helps fitness coaches generate Instagram Reel concepts, hooks, captions, hashtags, and related creative prompts. The output is designed to support faster content ideation, not to replace your own review or business judgment."
    ]
  },
  {
    title: "Accounts",
    body: [
      "You are responsible for keeping your login details secure and for activity that happens through your account. You must provide accurate information when creating or maintaining an account."
    ]
  },
  {
    title: "Subscriptions and billing",
    body: [
      "Paid plans are billed through Stripe on a recurring basis until canceled. The current paid plan pricing shown in the app or at checkout forms part of these Terms.",
      "You can manage or cancel your subscription through the Stripe customer portal linked inside the app. Unless required by law, payments already made are non-refundable."
    ]
  },
  {
    title: "Acceptable use",
    body: [
      "You agree not to misuse the service, reverse engineer it, interfere with its normal operation, attempt unauthorized access, or use it for unlawful, deceptive, or harmful activity.",
      "You remain responsible for the final content you publish using ideas generated by ReelFit AI, including compliance with platform rules, advertising rules, and consumer law."
    ]
  },
  {
    title: "Generated output",
    body: [
      "ReelFit AI generates creative suggestions automatically. Output may be similar to ideas shown to other users, may contain mistakes, and should be reviewed before posting, publishing, or relying on it commercially."
    ]
  },
  {
    title: "Availability and changes",
    body: [
      "We may update, improve, pause, or remove features from time to time. We aim to keep the service available, but we do not guarantee uninterrupted availability."
    ]
  },
  {
    title: "Limitation of liability",
    body: [
      "To the maximum extent permitted by law, ReelFit AI and SWEET MOTION are not liable for indirect, incidental, special, or consequential loss arising from your use of the service.",
      "Nothing in these Terms excludes rights or remedies that cannot lawfully be excluded under applicable law."
    ]
  },
  {
    title: "Termination",
    body: [
      "We may suspend or terminate access if these Terms are breached, if we are required to do so by law, or if continued access would create security, legal, or payment risk."
    ]
  },
  {
    title: "Updates to these Terms",
    body: [
      "We may update these Terms from time to time. If we make material changes, the updated version will be posted on this page with a refreshed effective date."
    ]
  }
];

export default function TermsPage() {
  return (
    <main className="container min-h-screen py-8">
      <div className="space-y-6">
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">
          <ArrowLeft className="h-4 w-4" />
          Back to ReelFit AI
        </Link>

        <div className="space-y-4">
          <BrandMark />
          <div className="flex flex-wrap items-center gap-3">
            <Badge>Terms of Service</Badge>
            <Badge variant="secondary">Effective 24 April 2026</Badge>
          </div>
          <div className="max-w-4xl space-y-3">
            <h1 className="font-hero text-5xl font-semibold text-balance">Simple terms for a simple product.</h1>
            <p className="max-w-3xl text-lg text-muted-foreground">
              ReelFit AI is a subscription web app operated by SWEET MOTION. These terms explain what the product does, what you can expect from it, and the basic rules around accounts, billing, and use.
            </p>
          </div>
        </div>

        <div className="grid gap-4 lg:grid-cols-3">
          <Card className="bg-background/70">
            <CardContent className="space-y-3 p-6">
              <div className="rounded-full bg-primary/10 p-3 text-primary w-fit">
                <FileText className="h-5 w-5" />
              </div>
              <h2 className="text-lg font-semibold">Clear scope</h2>
              <p className="text-sm text-muted-foreground">These terms cover the app, account usage, billing flows, and saved content history.</p>
            </CardContent>
          </Card>

          <Card className="bg-background/70">
            <CardContent className="space-y-3 p-6">
              <div className="rounded-full bg-primary/10 p-3 text-primary w-fit">
                <Sparkles className="h-5 w-5" />
              </div>
              <h2 className="text-lg font-semibold">Creative output</h2>
              <p className="text-sm text-muted-foreground">Generated ideas are a starting point. You remain responsible for your published content.</p>
            </CardContent>
          </Card>

          <Card className="bg-background/70">
            <CardContent className="space-y-3 p-6">
              <div className="rounded-full bg-primary/10 p-3 text-primary w-fit">
                <ShieldAlert className="h-5 w-5" />
              </div>
              <h2 className="text-lg font-semibold">Billing and access</h2>
              <p className="text-sm text-muted-foreground">Paid access runs through Stripe and can be managed from the customer portal inside the app.</p>
            </CardContent>
          </Card>
        </div>

        <Card className="max-w-5xl bg-background/70">
          <CardContent className="space-y-8 p-8">
            {sections.map((section) => (
              <section key={section.title} className="space-y-3">
                <h2 className="text-2xl font-semibold">{section.title}</h2>
                <div className="space-y-3 text-muted-foreground">
                  {section.body.map((paragraph) => (
                    <p key={paragraph}>{paragraph}</p>
                  ))}
                </div>
              </section>
            ))}

            <section className="space-y-3 rounded-[1.5rem] border border-primary/20 bg-primary/10 p-6">
              <h2 className="text-2xl font-semibold">Questions</h2>
              <p className="text-muted-foreground">
                For subscription issues, use the Stripe customer portal. For account or product questions, use the account email channel you signed up with until a dedicated support inbox is published.
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}
